sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build -t lawrence/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true lawrence/docker-react npm run test -- --coverage